name: Docker Images Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t MODNet-matting:latest .
